Check if L4T dir exists

diff --git a/pkg/bundled/cloudconfigs/30-prepare-l4t-rootfs.yaml b/pkg/bundled/cloudconfigs/30-prepare-l4t-rootfs.yaml
--- a/pkg/bundled/cloudconfigs/30-prepare-l4t-rootfs.yaml
+++ b/pkg/bundled/cloudconfigs/30-prepare-l4t-rootfs.yaml
@@ -8,7 +8,14 @@ stages:
           set -e
 
           TEGRA_DIR="Linux_for_Tegra"
-          cd "$TEGRA_DIR"
-          if [ ! -e bootloader/esp.img ]; then
-            ./apply_binaries.sh
+
+          if [ -d "$TEGRA_DIR" ]; then
+              cd "$TEGRA_DIR"
+              if [ ! -e bootloader/esp.img ]; then
+                ./apply_binaries.sh
+              fi
+          else
+              echo "Error: directory '$TEGRA_DIR' does not exist." >&2
+              exit 1
           fi
+          
